import {ColorValue, FlexAlignType, StyleProp, TextStyle} from 'react-native';

interface IBlock {
  flex?: number;
  noflex?: number;
  style?: StyleProp<TextStyle>;
  flexDirection?: 'row' | 'column' | 'row-reverse' | 'column-reverse';
  row?: any;
  white?: any;
  backgroundColor?: ColorValue;
  column?: any;
  center?: any;
  middle?: any;
  spaceBetween?: any;
  stretch?: any;
  relative?: any;
  absolute?: any;
  wrap?: any;
  opacity?: number;
  borderColor?: ColorValue;
  borderRadius?: number;
  zIndex?: number;
  right?: string | number;
  left?: string | number;
  top?: string | number;
  bottom?: string | number;
  width?: number | string;
  height?: number | string;
  alignItems?: FlexAlignType;
  borderStyle?: 'solid' | 'dotted' | 'dashed';
  borderWidth?: number;
  alignSelf?: FlexAlignType | 'auto';
  position?: 'absolute' | 'relative';
  maxWidth?: number;
  maxHeight?: number;
  minHeight?: number;
  minWidth?: number;
  padding?: number;
  paddingBottom?: number;
  paddingLeft?: number;
  paddingRight?: number;
  paddingTop?: number;
  margin?: number;
  marginBottom?: number;
  marginLeft?: number;
  marginRight?: number;
  marginTop?: number;
  spaceAround?: any;
  marginHorizontal?: any;
  paddingHorizontal?: any;
  marginVertical?: any;
  paddingVertical?: any;
}
