import React from 'react';
import {StyleProp, View, ViewStyle} from 'react-native';
import {heightScale, widthScale} from '../utils';
import {IBlock} from './@types/Block';

export const Block: React.FC<IBlock> = ({
  children,
  flex,
  style,
  row,
  white,
  noflex,
  backgroundColor,
  flexDirection,
  column,
  center,
  middle,
  spaceBetween,
  spaceAround,
  stretch,
  relative,
  absolute,
  wrap,
  opacity,
  borderColor,
  borderRadius,
  zIndex,
  right,
  left,
  top,
  bottom,
  width,
  height,
  alignItems,
  borderStyle,
  borderWidth,
  alignSelf,
  position,
  maxWidth,
  maxHeight,
  minHeight,
  minWidth,
  padding,
  paddingBottom,
  paddingLeft,
  paddingRight,
  paddingTop,
  margin,
  marginBottom,
  marginLeft,
  marginRight,
  marginTop,
  marginHorizontal,
  paddingHorizontal,
  marginVertical,
  paddingVertical,
}) => {
  const styleBlock: StyleProp<ViewStyle> = [
    style,
    row && {flexDirection: 'row'},
    flex && {flex: 1},
    typeof flex === 'number' && {flex},
    white && {backgroundColor: 'white'},
    noflex && {flex: 0},
    column && {flexDirection: 'column'},
    center && {alignItems: 'center'},
    middle && {justifyContent: 'center'},
    spaceBetween && {justifyContent: 'space-between'},
    spaceAround && {justifyContent: 'space-around'},

    stretch && {alignItems: 'stretch'},
    relative && {position: 'relative'},
    absolute && {position: 'absolute'},
    wrap && {flexWrap: 'wrap'},
    width && {width: widthScale(width)},
    height && {height: heightScale(height)},
    maxWidth && {maxWidth: widthScale(maxWidth)},
    maxHeight && {maxHeight: heightScale(maxHeight)},
    minHeight && {minHeight: heightScale(minHeight)},
    minWidth && {minWidth: widthScale(minWidth)},
    typeof width === 'string' && {width: width},
    typeof height === 'string' && {height: height},
    borderColor && {borderColor},
    borderRadius && {borderRadius: widthScale(borderRadius)},
    borderStyle && {borderStyle},
    borderWidth && {borderWidth},
    opacity && {opacity},
    zIndex && {zIndex},
    right && {right},
    left && {left},
    top && {top},
    bottom && {bottom},
    backgroundColor && {backgroundColor},
    alignItems && {alignItems},
    alignSelf && {alignSelf},
    flexDirection && {flexDirection},
    position && {position},
    padding && {padding: widthScale(padding)},
    paddingBottom && {paddingBottom: widthScale(paddingBottom)},
    marginLeft && {marginLeft: widthScale(marginLeft)},
    paddingLeft && {paddingLeft: widthScale(paddingLeft)},
    paddingRight && {paddingRight: widthScale(paddingRight)},
    paddingTop && {paddingTop: widthScale(paddingTop)},
    margin && {margin: widthScale(margin)},
    marginBottom && {marginBottom: widthScale(marginBottom)},
    marginLeft && {marginLeft: widthScale(marginLeft)},
    marginRight && {marginRight: widthScale(marginRight)},
    marginTop && {marginTop: widthScale(marginTop)},
    marginHorizontal && {marginHorizontal: widthScale(marginHorizontal)},
    paddingHorizontal && {paddingHorizontal: widthScale(paddingHorizontal)},
    marginVertical && {marginVertical: widthScale(marginVertical)},
    paddingVertical && {paddingVertical: widthScale(paddingVertical)},
  ];

  return <View style={styleBlock}>{children}</View>;
};
